// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpdqkybqvruqxizemvmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwZHFreWJxdnJ1cXhpemVtdm1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzQ1MzEsImV4cCI6MjA3MTYxMDUzMX0.FqtBaUzrlRdXJqfJ_1lORAT3mWTjcj_WW4MSucybMEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});